name: vamstreet_components
description: "The Vamstreet Component Library is a unified design system and modular codebase that powers both the Vamstreet Client application and Dashboard. This repository contains reusable UI components and design assets to maintain consistency across all Vamstreet products."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.13.0+15

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  fluent_ui: ^4.9.2
  cupertino_icons: ^1.0.8
  mocktail: ^1.0.4
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.4
  flutter_gen_runner:
  widgetbook_generator: ^3.9.0

flutter_gen:
  output: lib/src/core/utils/gen/assets # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: IranSansMobile_faNum_UltraLight
      fonts:
        - asset: assets/fonts/IRANSansMobile(FaNum)_UltraLight.ttf
          weight: 100
        - asset: assets/fonts/IRANSansMobile(FaNum)_UltraLight.ttf
          weight: 300
        - asset: assets/fonts/IRANSansMobile(FaNum)_UltraLight.ttf
          weight: 400
        - asset: assets/fonts/IRANSansMobile(FaNum)_UltraLight.ttf
          weight: 500
        - asset: assets/fonts/IRANSansMobile(FaNum)_UltraLight.ttf
          weight: 600
        - asset: assets/fonts/IRANSansMobile(FaNum)_UltraLight.ttf
          weight: 700

    - family: IranSansMobile_faNum_Light
      fonts:
        - asset: assets/fonts/IRANSansMobile(FaNum)_Light.ttf
          weight: 100
        - asset: assets/fonts/IRANSansMobile(FaNum)_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSansMobile(FaNum)_Light.ttf
          weight: 400
        - asset: assets/fonts/IRANSansMobile(FaNum)_Light.ttf
          weight: 500
        - asset: assets/fonts/IRANSansMobile(FaNum)_Light.ttf
          weight: 600
        - asset: assets/fonts/IRANSansMobile(FaNum)_Light.ttf
          weight: 700

    - family: IranSansMobile_faNum_Regular
      fonts:
        - asset: assets/fonts/IRANSansMobile(FaNum).ttf
          weight: 100
        - asset: assets/fonts/IRANSansMobile(FaNum).ttf
          weight: 300
        - asset: assets/fonts/IRANSansMobile(FaNum).ttf
          weight: 400
        - asset: assets/fonts/IRANSansMobile(FaNum).ttf
          weight: 500
        - asset: assets/fonts/IRANSansMobile(FaNum).ttf
          weight: 600
        - asset: assets/fonts/IRANSansMobile(FaNum).ttf
          weight: 700

    - family: IranSansMobile_faNum_Medium
      fonts:
        - asset: assets/fonts/IRANSansMobile(FaNum)_Medium.ttf
          weight: 100
        - asset: assets/fonts/IRANSansMobile(FaNum)_Medium.ttf
          weight: 300
        - asset: assets/fonts/IRANSansMobile(FaNum)_Medium.ttf
          weight: 400
        - asset: assets/fonts/IRANSansMobile(FaNum)_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSansMobile(FaNum)_Medium.ttf
          weight: 600
        - asset: assets/fonts/IRANSansMobile(FaNum)_Medium.ttf
          weight: 700

    - family: IranSansMobile_faNum_Bold
      fonts:
        - asset: assets/fonts/IRANSansMobile(FaNum)_Bold.ttf
          weight: 100
        - asset: assets/fonts/IRANSansMobile(FaNum)_Bold.ttf
          weight: 300
        - asset: assets/fonts/IRANSansMobile(FaNum)_Bold.ttf
          weight: 400
        - asset: assets/fonts/IRANSansMobile(FaNum)_Bold.ttf
          weight: 500
        - asset: assets/fonts/IRANSansMobile(FaNum)_Bold.ttf
          weight: 600
        - asset: assets/fonts/IRANSansMobile(FaNum)_Bold.ttf
          weight: 700

    - family: IranSansMobile_faNum_Black
      fonts:
        - asset: assets/fonts/IRANSansMobile(FaNum)_Black.ttf
          weight: 100
        - asset: assets/fonts/IRANSansMobile(FaNum)_Black.ttf
          weight: 300
        - asset: assets/fonts/IRANSansMobile(FaNum)_Black.ttf
          weight: 400
        - asset: assets/fonts/IRANSansMobile(FaNum)_Black.ttf
          weight: 500
        - asset: assets/fonts/IRANSansMobile(FaNum)_Black.ttf
          weight: 600
        - asset: assets/fonts/IRANSansMobile(FaNum)_Black.ttf
          weight: 700